name = "url_summarizer"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
jscheam = ">= 2.0.0 and < 3.0.0"
pig = { path = "../.." }
envoy = ">= 1.2.0 and < 2.0.0"
