#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPO_ROOT=""
TEMP_ROOT=""
WORKTREE_DIR=""
RELEASE_COMMIT=""
PIG_VERSION=""
PROTOCOL_VERSION=""
TRANSPORT_VERSION=""
PROXY_VERSION=""
PROXY_REQUESTED=0
PUBLISHED=()
ALREADY_PUBLISHED=()

fail() {
  printf '\n  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

cleanup() {
  if [[ -n "$WORKTREE_DIR" && -d "$WORKTREE_DIR" && -n "$REPO_ROOT" ]]; then
    git -C "$REPO_ROOT" worktree remove --force "$WORKTREE_DIR" >/dev/null 2>&1 || true
  fi
  if [[ -n "$TEMP_ROOT" && -d "$TEMP_ROOT" ]]; then
    rm -rf -- "$TEMP_ROOT"
  fi
}

trap cleanup EXIT

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

package_version() {
  local package_dir="$1"
  awk -F '"' '/^version = "/ { print $2; exit }' "$package_dir/gleam.toml"
}

validate_version() {
  local package="$1" version="$2"
  [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "$package has an unsupported version: $version"
}

validate_publishable_package() {
  local package="$1"
  local package_dir="$WORKTREE_DIR/packages/$package"
  local readme="$package_dir/README.md" config="$package_dir/gleam.toml"

  [[ -s "$readme" ]] || fail "$package requires a non-empty README.md before it can be published"
  if grep -Fq '// TODO: An example of the project in use' "$readme"; then
    fail "$package still has the default Gleam README.md"
  fi
  grep -Eq '^description = "[^"]+"' "$config" || fail "$package requires a description in gleam.toml"
  grep -Eq '^licences = \[[^]]+\]' "$config" || fail "$package requires at least one licence in gleam.toml"

  step "Build $package documentation to validate its HexDocs input."
  (cd "$package_dir" && gleam docs build)
}

release_exists() {
  local package="$1" version="$2" status
  status=$(curl -sS -o /dev/null -w '%{http_code}' \
    "https://hex.pm/api/packages/${package}/releases/${version}") || return 2
  case "$status" in
    200) return 0 ;;
    404) return 1 ;;
    *) return 2 ;;
  esac
}

wait_for_release() {
  local package="$1" version="$2"
  for _ in {1..30}; do
    if release_exists "$package" "$version"; then
      return 0
    fi
    sleep 2
  done
  return 1
}

publish_package() {
  local package="$1" version="$2" status
  local package_dir="$WORKTREE_DIR/packages/$package"

  if release_exists "$package" "$version"; then
    say "$package $version is already on Hex; skipping it."
    ALREADY_PUBLISHED+=("$package $version")
    return
  else
    status=$?
    [[ "$status" -eq 1 ]] || fail "could not check $package $version on Hex"
  fi

  step "Validate the $package $version Hex tarball."
  (cd "$package_dir" && gleam export hex-tarball)
  warn "Publishing $package $version is irreversible. Hex package versions cannot be reused."
  confirm "Publish $package $version now?" || fail "publication cancelled before $package $version"
  (cd "$package_dir" && gleam publish)
  wait_for_release "$package" "$version" || fail "$package $version was not visible on Hex after 60 seconds"
  PUBLISHED+=("$package $version")
  say "$package $version is available on Hex."
}

version_range() {
  local version="$1" major minor upper
  if [[ "$version" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
    major="${BASH_REMATCH[1]}"
    minor="${BASH_REMATCH[2]}"
  else
    fail "unsupported package version: $version"
  fi

  if (( major == 0 )); then
    upper="0.$((minor + 1)).0"
  else
    upper="$((major + 1)).0.0"
  fi
  printf '>= %s and < %s' "$version" "$upper"
}

replace_path_dependency() {
  local file="$1" dependency="$2" range="$3" replacement tmp
  replacement="$dependency = \"$range\""
  tmp=$(mktemp)
  awk -v dependency="$dependency" -v replacement="$replacement" '
    BEGIN { found = 0; invalid = 0 }
    $0 ~ ("^" dependency "[[:space:]]*=") {
      found++
      if ($0 ~ /path[[:space:]]*=/ || $0 == replacement) {
        print replacement
      } else {
        invalid = 1
        print
      }
      next
    }
    { print }
    END {
      if (found != 1) exit 2
      if (invalid) exit 3
    }
  ' "$file" > "$tmp" || {
    rm -f "$tmp"
    fail "could not replace $dependency in $file"
  }
  mv "$tmp" "$file"
}

prepare_dependent_package() {
  local package="$1"
  local package_dir="$WORKTREE_DIR/packages/$package"
  replace_path_dependency "$package_dir/gleam.toml" pig_protocol "$(version_range "$PROTOCOL_VERSION")"
  replace_path_dependency "$package_dir/gleam.toml" pig_transport "$(version_range "$TRANSPORT_VERSION")"
  (cd "$package_dir" && gleam deps download)

  if grep -Eq 'name = "(pig_protocol|pig_transport)".*source = "local"' "$package_dir/manifest.toml"; then
    fail "$package still has local Pig dependencies after manifest regeneration"
  fi

  step "Build and test $package against the released Hex dependencies."
  (cd "$package_dir" && gleam build --warnings-as-errors && gleam test)
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  cat <<'EOF'
Usage: scripts/publish.sh

Interactively publish the Pig monorepo packages from an up-to-date main branch.
The wizard publishes pig_protocol and pig_transport first, then prepares
release-only dependency ranges in a temporary worktree and publishes pig. It
optionally publishes pig_proxy. Gleam authentication and confirmation prompts
remain interactive.
EOF
  trap - EXIT
  exit 0
fi
[[ "$#" -eq 0 ]] || fail "unknown argument: $1"
[[ -t 0 ]] || fail "this release wizard requires an interactive terminal"

banner "Pig Hex release"

stage "Preflight and validation"
say "First we verify merged main, run the project gates, and create an isolated release worktree."
for command in git gleam mise curl awk grep mktemp; do
  require_command "$command"
done
command -v cc >/dev/null 2>&1 || fail "C compiler 'cc' is required to build pig's esqlite dependency; install GCC or Clang"
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || fail "run this script from the Pig Git repository"
[[ "$(git -C "$REPO_ROOT" branch --show-current)" == "main" ]] || fail "switch to main after PR #28 merges"
[[ -z "$(git -C "$REPO_ROOT" status --porcelain --untracked-files=no)" ]] || fail "tracked files on main must be clean"
step "Fetch origin/main and confirm this checkout is fully up to date."
git -C "$REPO_ROOT" fetch origin main
RELEASE_COMMIT=$(git -C "$REPO_ROOT" rev-parse HEAD)
[[ "$RELEASE_COMMIT" == "$(git -C "$REPO_ROOT" rev-parse origin/main)" ]] || fail "local main does not match origin/main"
TEMP_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/pig-release.XXXXXX")
WORKTREE_DIR="$TEMP_ROOT/repo"
git -C "$REPO_ROOT" worktree add --detach "$WORKTREE_DIR" "$RELEASE_COMMIT"
PIG_VERSION=$(package_version "$WORKTREE_DIR/packages/pig")
PROTOCOL_VERSION=$(package_version "$WORKTREE_DIR/packages/pig_protocol")
TRANSPORT_VERSION=$(package_version "$WORKTREE_DIR/packages/pig_transport")
PROXY_VERSION=$(package_version "$WORKTREE_DIR/packages/pig_proxy")
validate_version pig "$PIG_VERSION"
validate_version pig_protocol "$PROTOCOL_VERSION"
validate_version pig_transport "$TRANSPORT_VERSION"
validate_version pig_proxy "$PROXY_VERSION"
say "Release set: pig $PIG_VERSION, pig_protocol $PROTOCOL_VERSION, pig_transport $TRANSPORT_VERSION, pig_proxy $PROXY_VERSION."
if confirm "Include the optional pig_proxy $PROXY_VERSION release?"; then
  PROXY_REQUESTED=1
else
  say "pig_proxy will be skipped."
fi
confirm "Run the full test and build gates?" || fail "release validation cancelled"
(cd "$WORKTREE_DIR" && mise run test && mise run build)
validate_publishable_package pig_protocol
validate_publishable_package pig_transport
validate_publishable_package pig
if (( PROXY_REQUESTED )); then
  validate_publishable_package pig_proxy
fi

stage "Publish pig_protocol"
say "pig_protocol must exist on Hex before the dependent packages can resolve it."
publish_package pig_protocol "$PROTOCOL_VERSION"

stage "Publish pig_transport"
say "pig_transport must exist on Hex before pig or pig_proxy can be published."
publish_package pig_transport "$TRANSPORT_VERSION"

stage "Prepare dependent packages"
say "The temporary worktree will use bounded Hex ranges instead of monorepo paths."
prepare_dependent_package pig
if (( PROXY_REQUESTED )); then
  prepare_dependent_package pig_proxy
fi
say "Release-only manifests are ready. Your main checkout is unchanged."

stage "Publish pig"
say "The core library now resolves the released protocol and transport packages from Hex."
publish_package pig "$PIG_VERSION"

stage "Optional pig_proxy publication"
if (( PROXY_REQUESTED )); then
  say "The optional proxy was selected during preflight and now resolves its Pig dependencies from Hex."
  publish_package pig_proxy "$PROXY_VERSION"
else
  say "pig_proxy is not required by library users and was skipped by request."
fi

stage "Verify and clean up"
say "Verify every requested release before removing the temporary worktree."
release_exists pig_protocol "$PROTOCOL_VERSION" || fail "pig_protocol $PROTOCOL_VERSION is missing from Hex"
release_exists pig_transport "$TRANSPORT_VERSION" || fail "pig_transport $TRANSPORT_VERSION is missing from Hex"
release_exists pig "$PIG_VERSION" || fail "pig $PIG_VERSION is missing from Hex"
if (( PROXY_REQUESTED )); then
  release_exists pig_proxy "$PROXY_VERSION" || fail "pig_proxy $PROXY_VERSION is missing from Hex"
fi
cleanup
trap - EXIT
finish
if (( ${#PUBLISHED[@]} )); then
  note "published: ${PUBLISHED[*]}"
fi
if (( ${#ALREADY_PUBLISHED[@]} )); then
  note "already published: ${ALREADY_PUBLISHED[*]}"
fi
if (( ! PROXY_REQUESTED )); then
  note "pig_proxy $PROXY_VERSION was not requested"
fi
note "main remains unchanged at $RELEASE_COMMIT"
